### ISSUE TITLE
Enabling .withFormatter functionality on vaadin applications

### ISSUE THREAD

**Issue by lifeanddeath** [appreciated/apexcharts-flow#101]
**Is your feature request related to a problem? Please describe.**
In my vaadin application, I'm using radial bar chart. There is a value and label shown within this circular radial bar. However, I need to manipulate the percentage value and say instead of showing 75%, i want to show A or B value. This is achievable with .withFormatter option in datalabel section but I guess current java wrapper does not support it, as it plots to view nothing at all.

**Describe the solution you'd like**
withFormatter method can take a string value and replace it with the actual value.

**Additional context**
Currently, if i return null from this method, it shows the visual totally fine, but anything else than null causes visual to be corrupted and not shown at all.

**Comment by mvysny** [comment]
ApexCharts wrapper currently doesn't support setting a formatter function, see #92 for more details.

**Comment by appreciated** [comment]
closed by 78505a3cca83734defeec58fc15c809098eecaa1
