### ISSUE TITLE
Source out of sync with deployed version?

### ISSUE THREAD

**Issue by theshoeshiner** [appreciated/apexcharts-flow#118]
The source appears to be out of sync with the deployed version. The deployed version contains the method:

`com.github.appreciated.apexcharts.config.xaxis.builder.LabelsBuilder.withDateTimeUTC(Boolean)`

But this method is not present in the source, including the source attached to the deployed jar. I'm planning on forking the code to add some new config parameters, but I wanted to double check to see if the code is actually up to date with what I'm using from the maven repo.

Edit:
Same issue with the method below. In deployed version it accepts an array.

`com.github.appreciated.apexcharts.ApexChartsBuilder.withXaxis(XAxis)`

Edit:
Or is this a permissions issue? The readme mentions multiple branches, but all I see is the master and dependabot branches.

**Comment by appreciated** [comment]
The code was merged, but not yet released. Currently, preparing a new release 🙂
