### ISSUE TITLE
Some charts has unnecessary space(margin) on top

### ISSUE THREAD

**Issue by ugurdoksan** [appreciated/apexcharts-flow#12]
The code is the same with your Demo code.
You can see in the ss below (the red lined unnecessary spaces).

![Capture](https://user-images.githubusercontent.com/24225109/56855228-79003b00-694c-11e9-8061-14208cec8f94.PNG)

**Comment by appreciated** [comment]
This comes from the `<form-layout>`
![grafik](https://user-images.githubusercontent.com/1729845/56855602-2291fd00-694a-11e9-9af5-dfd5412cd3ae.png)

**Comment by ugurdoksan** [comment]
Why the other charts on the top except line charts? They are all in the same formlayout.

**Comment by appreciated** [comment]
@ugurdoksan Because these are higher

**Comment by appreciated** [comment]
The easiest fix I found for this problem:
```
for (ApexCharts chart : generator.getCharts()) {
    chart.getStyle().set("align-self","center");
    add(chart);
}
```
