### ISSUE TITLE
Support for Vaadin 15+...?

### ISSUE THREAD

**Issue by markhm** [appreciated/apexcharts-flow#130]
From its [component page](https://vaadin.com/directory/component/apexchartsjs/) in the Vaadin Directory, I understand that up to Vaadin version to 14.7.5 is supported by ApexCharts-Flow v2.0.0-BETA13. Of course, this is because the component is based on the PolymerTemplate. 

Is there a plan to port apexcharts-flow to LitTemplate...? 🙏🏻

**Comment by amagnolo** [comment]
in my experience the component works with Vaadin 23, but it breaks if compiled for production using Vite.
