### ISSUE TITLE
Version 0.8.0 not working on Tomcat Server

### ISSUE THREAD

**Issue by ugurdoksan** [appreciated/apexcharts-flow#15]
_0.8.0 Demo Code_ 

- Works well on Jetty 👍  (Latest version of Jetty)

- Does not work in Tomcat Application Server 👎 (Latest version of Tomcat)

Vaadin Version: **13.0.5**

There is **not** any error log in Tomcat logs, but there is an error on Browser logs(Latest version of Chrome).

I got error when I upgraded to version **0.8.0** with new demos. 

![Capture](https://user-images.githubusercontent.com/24225109/56952743-ac58ea80-6b43-11e9-9eca-8bae4c33d216.PNG)

**Comment by ugurdoksan** [comment]
Details of Chrome Logs:

![Capture](https://user-images.githubusercontent.com/24225109/57184857-baec2c80-6eca-11e9-886f-2f1c543d2021.PNG)

**Comment by appreciated** [comment]
Thanks for reporting, will fix as soon as I got time, I'm currently rather busy with work and university.

**Comment by watho** [comment]
Just wanted to add, that this is no tomcat problem, but same like here: https://github.com/appreciated/vaadin-app-layout/issues/154

It's working with root context-path.

**Comment by ugurdoksan** [comment]
Is not there any plan to fix this bug? There is not any commit for this project since 3 weeks. If I could I would try to fix the bug. I am waiting impatiently :(

**Comment by appreciated** [comment]
> Is not there any plan to fix this bug? 

There is, as I already stated above, as being said, I'm currently heavily busy with another project.  

> If I could I would try to fix the bug. 

So what is holding you back 🙂?

**Comment by appreciated** [comment]
Please check if 0.9 fixes this issue

**Comment by ugurdoksan** [comment]
@appreciated It works fine.. Thanks 👍
