### ISSUE TITLE
New Release of apexcharts-flow

### ISSUE THREAD

**Issue by stadler** [appreciated/apexcharts-flow#154]
apexcharts-flow hasn't been released for a year.
Would it maybe be possible to make another release of it, that includes the latest features/bugfixes?
Could we expect the release to still be Vaadin 14 compatible?
Thanks for keeping up the good work!

**Comment by TFyre** [comment]
Latest release has been done 2 months ago.

Vaadin 23
Available here: https://vaadin.com/directory/component/apexchartsjs

**Comment by stadler** [comment]
Oh, nice. Thanks!
I would have expected the release to appear in the GitHub Releases: https://github.com/appreciated/apexcharts-flow/releases
Maybe this could be added? E.g. like [this](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).

**Comment by TFyre** [comment]
Done :)

https://github.com/appreciated/apexcharts-flow/releases/tag/v23.0.0

Closing
