### ISSUE TITLE
[TypeScript] Could not find a declaration file for module 'onecolor'. 

### ISSUE THREAD

**Issue by mamungm** [appreciated/apexcharts-flow#159]
**Describe the bug**
[TypeScript] Could not find a declaration file for module 'onecolor'. '/Users/mamungm/Desktop/Development/bitbucket/bond/engine/node_modules/onecolor/index.js' implicitly has an 'any' type. Try `npm i --save-dev @types/onecolor` if it exists or add a new declaration (.d.ts) file containing `declare module 'onecolor';`
/Users/mamungm/Desktop/Development/bitbucket/bond/engine/frontend/generated/jar-resources/com/github/appreciated/apexcharts/apexcharts-wrapper.ts:6:19
    4 | import ApexCharts from 'apexcharts/dist/apexcharts.esm';
    5 | import '@webcomponents/shadycss/apply-shim.min.js';
  > 6 | import color from "onecolor";
      |                   ^^^^^^^^^^
    7 |
    8 | @customElement('apex-charts-wrapper')
    9 | export class ApexChartsWrapper extends LitElement {

**Steps or code example to Reproduce**
Install and run a view

or if the bug occurs when using a specific chart type
```
ApexCharts pieChart = new ApexCharts()
...
return pieChart;
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

implementation("com.github.appreciated:apexcharts:23.0.0")
plugins {
	java
	id("org.springframework.boot") version "2.7.5"
	id("io.spring.dependency-management") version "1.1.0"
	id("com.vaadin") version "23.2.12"
}

**Comment by appreciated** [comment]
Try with the new version in the Vaadin directory. Reopen if the issue still occurs.
