### ISSUE TITLE
Vaadin 24 support

### ISSUE THREAD

**Issue by bsutton** [appreciated/apexcharts-flow#163]
Just wondering if there is an ETA on Vaadin 24 support?

**Comment by mpkeusch** [comment]
Any updates on this?
There seems to be a PR with Vaadin 24 support:

https://github.com/appreciated/apexcharts-flow/pull/164

Thanks

**Comment by appreciated** [comment]
Fixed by 92847db3ce1913f62fb6f1dc93a67b5de8db0688
