### ISSUE TITLE
Missing apexcharts.js and chroma.js

### ISSUE THREAD

**Issue by jharahuld** [appreciated/apexcharts-flow#17]
![Screenshot from 2019-05-27 17-58-22](https://user-images.githubusercontent.com/4396651/58553225-01b31500-8232-11e9-918a-6fb9c6e1ef82.png)

**Comment by appreciated** [comment]
Can you provide information about what Servlet Container, which Vaadin version and which pluging version?

**Comment by appreciated** [comment]
Servlet Container?

**Comment by jharahuld** [comment]
Servlet Container 3.0

**Comment by appreciated** [comment]
I meant if it's Jetty/Tomcat/Wildfly ...

**Comment by jharahuld** [comment]
Tomcat V8.0

**Comment by ugurdoksan** [comment]
It looks the same situation with #15

**Comment by jharahuld** [comment]
Edited script src value as tomcat app context path From
`<script src="../../../../../webjars/apexcharts/3.6.8/dist/apexcharts.js"></script>
<script src="../../../../../webjars/chroma-js/1.1.1/chroma.js"></script>`
To
`<script src="../../../webjars/apexcharts/3.6.8/dist/apexcharts.js"></script>
<script src="../../../webjars/chroma-js/1.1.1/chroma.js"></script>`

**Comment by appreciated** [comment]
@jharahuld does Version `0.9.0` fix this for you

**Comment by ugurdoksan** [comment]
It is fixed with the `0.9.0` version

**Comment by jharahuld** [comment]
> @jharahuld does Version `0.9.0` fix this for you?

Yes after changing context path it does

**Comment by appreciated** [comment]
> Yes after changing context path it does.
@jharahuld It needs to work without changing the context path.
Does it or does it not?

**Comment by jharahuld** [comment]
> > Yes after changing context path it does.
> 
> @jharahuld It needs to work without changing the context path.
> Does it or does it not?

as @ugurdoksan said may be it is working i dont know because i am still using version 0.8.0
