### ISSUE TITLE
Show percent in tooltip

### ISSUE THREAD

**Issue by jkoenig134** [appreciated/apexcharts-flow#18]
Hey, is it possible to show the percent in tooltip and not just the value and to show Integer values instead of double?

**Comment by appreciated** [comment]
@jkoenig134 Tooltip in which chart type? Have you checked the official documentation? 
>  to show Integer values instead of double?
Currently, not but I guess it is just a matter of presentation.

**Comment by jkoenig134** [comment]
@appreciated i am using the pie chart. I could´t find out something.

**Comment by appreciated** [comment]
Closed by e0f68054f61f26fab0c3999f9c77f494bf88d8e1

**Comment by jkoenig134** [comment]
Thank you!
