### ISSUE TITLE
Cannot set color to yaxis label

### ISSUE THREAD

**Issue by karl9821** [appreciated/apexcharts-flow#181]
this is my code for setting up yaxis

`    // Setting y-axis labels
    YAxis yAxis = YAxisBuilder.get()

        .withLabels(LabelsBuilder.get()
            .withFormatter(
                "function(val) { if (val >= 1000000) { return (val / 1000000).toFixed(1) + 'M'; } else { return val / 1000 + 'K'; } }")
            .withStyle(com.github.appreciated.apexcharts.config.yaxis.labels.builder.StyleBuilder.get()
                .withColor("#FFFFFF").build())
            .build())
        .withTooltip(TooltipBuilder.get().withEnabled(false).build())
        .build();
    chart.setYaxis(new YAxis[] { yAxis });`
This is the result i can change the xaxis color but it does not seem to work on the yaxis label
![Snag_154c4242](https://github.com/appreciated/apexcharts-flow/assets/89179024/390cacb3-291a-448a-a4c0-402f522527c3)

**Comment by karl9821** [comment]
After encountering an issue with ApexCharts where the y-axis label font color wasn't being applied, I found an alternative solution. By setting the theme to dark mode, which made all fonts white, and adjusting the background of the chart to match my page, I achieved the desired result.

**Comment by Loahrs** [comment]
Another solution would be to set a cssClassName: 

```
.withYaxis(YAxisBuilder.get()
        .withLabels(LabelsBuilder.get()
                .withStyle(StyleBuilder.get()
                        .withCssClass("custom-y-axis-label")
                        .build())
                .build())
        .build())
.build()
```

and then you can change the textcolor like:

```
.custom-y-axis-label{
   fill: orange;
}
```
