### ISSUE TITLE
Add an updateConfig method

### ISSUE THREAD

**Issue by Bethibande** [appreciated/apexcharts-flow#189]
**Is your feature request related to a problem? Please describe.**
There are methods like ApexCharts.setTitle, for example. However, the changes made using these methods are not applied to the cart.
It seems the config is never updated after creating the chart.

**Describe the solution you'd like**
I wish to propose a `updateConfig` method like this:
```java
public void updateConfig() {
    getElement().callJsFunction("updateConfigAndApply");
}
```
```ts
updateConfigAndApply() {
    this.updateConfig();
    this.chartComponent.updateOptions(this.config);
}
```

**Describe alternatives you've considered**
Adding the following to the end of the `updateConfig` typescript function in `apexcharts-wrapper.ts` doesn't work:
```ts
this.chartComponent.updateOptions(this.config)
```
Calling `chart.render()` also doesn't work.

**Additional context**
You can test/reproduce this using the following class:
https://gist.github.com/Bethibande/4b8e82640bda7548ebbc2cd5a123fb26

After looking at other issues, which I should've done from the start. I discovered that this is pretty much what was already proposed for #147

**Comment by Loahrs** [comment]
Supported through #190
