### ISSUE TITLE
Latest release 24.0.1 has broken chart types

### ISSUE THREAD

**Issue by mcfar3199** [appreciated/apexcharts-flow#196]
**Describe the bug**
I'm using apex charts to generate area, bar, line, and scatter charts. All of these charts are working in 24.0.0, but they are not after I updated my pom to 24.0.1

or if the bug occurs when using a specific chart type
1. Create an apex chart and load with IntegerSeries data.
2. Generate a bar chart, works fine.
3. Generate one of the other types of charts and all the data is stacked in the center of the chart on the Y axis.

**Expected behavior**
It should work like it did in the previous release.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOs Monterey
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 129.0.6668.100

**Comment by Loahrs** [comment]
Hey, does the problem consist? 

I am not sure if there were any changes in 24.0.1 compared to 24.0.0 in the library itself. Do you mean (or have you tried) 24.0.2?

I wasn't able to reproduce the problem yet. Could you maybe provide a code snippet that shows the problem? That would be very helpful! :)

**Comment by mcfar3199** [comment]
I put together a small bare bones sample project and am not able to reproduce the error. The chart types all work. So it must be something that changed in the 24.0.1 release that impacts how I am building the charts. My code does work on the 24.0.0 code base, but the area and line charts in particular do not after I update to 24.0.1. I will continue debugging and see if I can discover what part of my code the charts don't like. Could you point me to the release notes so I can see what exactly changed between the versions? Thank you for your response, this is an awesome add-on and very useful for my application.
