### ISSUE TITLE
Lumo Theme support

### ISSUE THREAD

**Issue by appreciated** [appreciated/apexcharts-flow#2]
Light and Dark variant

**Comment by ugurdoksan** [comment]
I got error when I upgraded to version 0.8.0 with new demos
![Capture](https://user-images.githubusercontent.com/24225109/56952482-1a50e200-6b43-11e9-92b3-3763312c1949.PNG)

**Comment by ugurdoksan** [comment]
The colors has gone, it think the colorful charts looks better and more understandable than the new ones. 
There is now only one color (blue) and its tones :(
