### ISSUE TITLE
one-color.js not found

### ISSUE THREAD

**Issue by JozefKuco** [appreciated/apexcharts-flow#21]
after updating apexcharts in pom.xml from 0.8.0 to 0.9.0 and running `mvn clean package -Pproduction-mode` it cannot find onecolor file

`[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:13.0.7:package-for-production (default) on project ................: Execution default of goal com.vaadin:vaadin-maven-plugin:13.0.7:package-for-production failed: An import that ends with '../webjars/onecolor/3.0.5/one-color.js' cannot be resolved: the corresponding file '.........................................\target\frontend\..\webjars\onecolor\3.0.5\one-color.js' was not found.`

`[ERROR] Double check the corresponding import and verify the following:`

`[ERROR] * the import string is correct`

`[ERROR] * the file imported is either present in 'frontend://' directory of the project or in one of the project WebJar dependencies or in one of the regular jar dependencies`

`[ERROR] * if the file is present in one of the regular jar dependencies, it should be located in META-INF/resources/frontend directory in the jar`

**Comment by nrapel** [comment]
Same problem here.. While 0.8.0 creates the production .war the 0.9.0 is stuck on ..\webjars\onecolor\3.0.5\one-color.js' was not found.
Any hints on how to fix this? (Don't want to go to 14 version just yet!!)

**Comment by appreciated** [comment]
@nrapel If you provide a minimal none working example for me to reproduce the issue, I'll take a look into this.

**Comment by nrapel** [comment]
No need to do much.. At the "starter project" of Vaadin 13, (version 13.0.13) just add the dependency at the my-starter-project-ui/pom.xml 
 
<dependency>
	  <groupId>com.github.appreciated</groupId>
	  <artifactId>apexcharts</artifactId>
	   <version>0.9.0</version>
</dependency>

And then run 
mvn clean package -PproductionMode (or mvn clean package -Pproduction-mode depending  at the profile name) .. 
The return is this: 

`[INFO] --- vaadin-maven-plugin:13.0.13:package-for-production (default) @ my-starter-project-ui ---
[WARNING] The translated URL 'frontend://bower_components/vaadin-upload/theme/lumo/vaadin-upload-file.html' has no corresponding file on the filesystem, the file is addressed by path='C:\Javawork\vaadin_workspace_10\my-starter-project-13\my-starter-project-ui\target\frontend\bower_components\vaadin-upload\theme\lumo\vaadin-upload-file.html'
[WARNING] The translated URL 'frontend://theme/lumo/apexcharts/apexcharts-wrapper.html' has no corresponding file on the filesystem, the file is addressed by path='C:\Javawork\vaadin_workspace_10\my-starter-project-13\my-starter-project-ui\target\frontend\theme\lumo\apexcharts\apexcharts-wrapper.html'
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] My Starter Project 1.0-SNAPSHOT .................... SUCCESS [  0.264 s]
[INFO] My Starter Project-backend ......................... SUCCESS [  5.495 s]
[INFO] My Starter Project-ui 1.0-SNAPSHOT ................. FAILURE [ 12.530 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.637 s
[INFO] Finished at: 2019-09-23T15:30:17+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:13.0.13:package-for-production (default) on project my-starter-project-ui: Execution default of goal com.vaadin:vaadin-maven-plugin:13.0.13:package-for-production failed: An import that ends with '../webjars/onecolor/3.0.5/one-color.js' cannot be resolved: the corresponding file 'C:\Javawork\vaadin_workspace_10\my-starter-project-13\my-starter-project-ui\target\frontend\..\webjars\onecolor\3.0.5\one-color.js' was not found.
[ERROR] Double check the corresponding import and verify the following:
[ERROR] * the import string is correct
[ERROR] * the file imported is either present in 'frontend://' directory of the project or in one of the project WebJar dependencies or in one of the regular jar dependencies
[ERROR] * if the file is present in one of the regular jar dependencies, it should be located in `META-INF/resources/frontend` directory in the jar
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.`

**Comment by JozefKuco** [comment]
@nrapel @appreciated did u find any workaround?

**Comment by jharahuld** [comment]
I have tried with version 2.0.0.beta1 and able to create a production build successfully

**Comment by nrapel** [comment]
The same thing happens in 14.1.5 if you use the bower mode (compatibility mode). My "workaround" is to use an older version (0.5.0 is the one that I got it working with), since the latest version don't support compatibility mode (bower) but only npm.

**Comment by jharahuld** [comment]
> The same thing happens in 14.1.5 if you use the bower mode (compatibility mode). My "workaround" is to use an older version (0.5.0 is the one that I got it working with), since the latest version don't support compatibility mode (bower) but only npm.

Is this works with vaadin 13.0.11 ?

**Comment by jharahuld** [comment]
@appreciated any solution for vaadin 13.0.11 production build?

**Comment by appreciated** [comment]
Sorry but I am not giving support for Vaadin 13, especially since I'm highly busy at the moment. 
I recommend upgrading to V14 + NPM. 
Note that Vaadin 13 has no support at all, so upgrading is anyways highly recommended.

**Comment by jharahuld** [comment]
> Sorry but I am not giving support for Vaadin 13, especially since I'm highly busy at the moment.
> I recommend upgrading to V14 + NPM.
> Note that Vaadin 13 has no support at all, so upgrading is anyways highly recommended.

Can you please share the source code for Vaadin 13 !

**Comment by appreciated** [comment]
> Can you please share the source code for Vaadin 13 !
[It is right here](https://github.com/appreciated/apexcharts-flow/tree/b35949a08d8a1a02be02e0e2b99b1548f56f8613).

**Comment by jharahuld** [comment]
> > Can you please share the source code for Vaadin 13 !
> 
> [It is right here](https://github.com/appreciated/apexcharts-flow/tree/b35949a08d8a1a02be02e0e2b99b1548f56f8613).

Master branch is compatible with vaadin 13 ?

**Comment by appreciated** [comment]
>>>        Can you please share the source code for Vaadin 13 !

>>    It is right here.

> Master branch is compatible with vaadin 13 ?

Not in general, but this commit was.

**Comment by jharahuld** [comment]
> > > > ```
> > > >    Can you please share the source code for Vaadin 13 !
> > > > ```
> 
> > > It is right here.
> 
> > Master branch is compatible with vaadin 13 ?
> 
> Not in general, but this commit was.

Ok
