### ISSUE TITLE
Path Attribute Exception

### ISSUE THREAD

**Issue by ugurdoksan** [appreciated/apexcharts-flow#22]
Vaadin Version: **14.0.0.rc2**
Apexcharts Version: **0.9.0**
Java Version: **11**
Browser: Chrome or Yandex (Latest Versions -> Windows)

![Capture](https://user-images.githubusercontent.com/24225109/60255011-a11e0300-98d7-11e9-9ec1-41c18176b444.PNG)

**Comment by appreciated** [comment]
@ugurdoksan seems to be fixed in the `2.0.0 beta1` version
