### ISSUE TITLE
The XAxis does not use the Labels Class

### ISSUE THREAD

**Issue by Rahul-Bhargav** [appreciated/apexcharts-flow#24]
The Xaxis builder does not use the Labels class. So we cannot configure the labels, formatting etc.
Tried to Fix it but the encoder doesn't work in a way I wanted it to. I hope this is a small fix.

**Comment by appreciated** [comment]
@Rahul-Bhargav Please add more details to this issue, otherwise I have to dig a lot on what is not working, and believe me I've got to do much more things to do. Also please consider making a pull request.  

Give an examples of what you want to archive, how you want it to archive. 
Also please add some code to show what is not working as exspected.

**Comment by Rahul-Bhargav** [comment]
Hello! Sorry for not being very specific. Will give you some context about the issue.
The current code works perfectly fine. However there is a slight problem.

The current code base does not support having a chart configuration like this, where XAxis has labels with custom properties.

```
xaxis: {
    . . . ,
    labels: {
        show: true,
        rotate: -45,
        rotateAlways: false,
        hideOverlappingLabels: true,
        showDuplicates: false,
        trim: true,
        minHeight: undefined,
        maxHeight: 120,
        style: {
            colors: [],
            fontSize: '12px',
            fontFamily: 'Helvetica, Arial, sans-serif',
            cssClass: 'apexcharts-xaxis-label',
        },
        offsetX: 0,
        offsetY: 0,
        format: undefined,
        formatter: undefined,
        datetimeFormatter: {
            year: 'yyyy',
            month: "MMM 'yy",
            day: 'dd MMM',
            hour: 'HH:mm',
        },
    },
    . . .
}
```
The XAxis Class (in config) uses a `List<String>` for labels instead of the Labels class. Surprisingly the YAxis class uses the Labels class. Not really sure if this was something that happened due to a specific issue or a request. Currently I am somehow trying to inject into the code using some polymer templates. There has to be a more elegant way of doing this.

I will fork the repo and try to get it to work, but I'm super new to vaadin and polymer.

Hope this cleared my issue for you. 👍

**Comment by appreciated** [comment]
@Rahul-Bhargav thank you very much for updating this. Now I got it 😉. Please check in the upcoming version if the issue was fixed for you!

**Comment by Rahul-Bhargav** [comment]
Thanks for the Update will check it out and let you know.
