### ISSUE TITLE
Allow to updates series with animation. 

### ISSUE THREAD

**Issue by appreciated** [appreciated/apexcharts-flow#26]

**Comment by Lightbringer19** [comment]
Hello, I can't figure out how to update series. https://github.com/Lightbringer19/apex-test/blob/master/src/main/java/com/gmail/vladimir/spring/MainView.java Here is a simple demo with an area chart and a button that should update series. When I click the button nothing happens. I've tried different approaches, maybe I'm doing something wrong?

**Comment by appreciated** [comment]
Will try to check it out this evening sorry you are having issues with this.
