### ISSUE TITLE
Version 2.0.0.beta2 (demo code) not working with Vaadin 14.0.1

### ISSUE THREAD

**Issue by ugurdoksan** [appreciated/apexcharts-flow#28]
**Code:** Demo Code
**Application Server:** Tomcat 9.0 or Jetty
**Vaadin Version:** 14.0.1
**ApexCharts Version:** 2.0.0.beta2
**Browser:** Any browser with the latest version (Windows)

Note: There is not any error on the screen or on the browser console. There is only a blank window.

![SS](https://user-images.githubusercontent.com/24225109/63295179-b2323180-c2d4-11e9-8338-ef33e0544663.PNG)

**Comment by appreciated** [comment]
Are you using compatiblity Mode?

**Comment by appreciated** [comment]
Using the demo code in combination with a freshly generated sample application works by the way just fine.
```
mvn -B archetype:generate -DarchetypeGroupId=com.vaadin -DarchetypeArtifactId=vaadin-archetype-application -DarchetypeVersion=LATEST -DgroupId=org.test -DartifactId=vaadin-app -Dversion=1.0-SNAPSHOT
```

**Comment by appreciated** [comment]
@ugurdoksan can you check if [a downgrade to 14.0.0 fixes your issue](https://github.com/vaadin/flow/issues/6288).

**Comment by ugurdoksan** [comment]
@appreciated Yes, I am using **flow-server-compatibility-mode** dependency.

I think it is not only related to Tomcat => Also the problem occurs in the Jetty Server too.

I downgraded to 14.0.0 but the problem is not solved.

**Comment by ugurdoksan** [comment]
Here is the browser console. (There is not any error)

![ss](https://user-images.githubusercontent.com/24225109/63343257-311b7e80-c356-11e9-96c2-eb35072c029e.PNG)

**Comment by appreciated** [comment]
> Here is the browser (cache cleared) console. (There is not any error)
Does chrome may give some other output?

**Comment by ugurdoksan** [comment]
@appreciated Here is the Chrome (cache cleared) console. (There is not any error)

![Capture](https://user-images.githubusercontent.com/24225109/63456847-7b852400-c458-11e9-90fe-d74c0104c738.PNG)

**Comment by appreciated** [comment]
Can you please checked if this was fixed in `2.0.0.beta3`?

**Comment by ugurdoksan** [comment]
I've tried with **ApexCharts Version: 2.0.0.beta4** but the problem is not solved.

**Comment by appreciated** [comment]
Is you webpack actually running through without any issues?

**Comment by appreciated** [comment]
This issue was fixed with Vaadin `14.0.5`

**Comment by ugurdoksan** [comment]
I've tried with Vaadin 14.0.6 than I've taken an error on Tomcat.

_Caused by: java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'apex-charts-wrapper' in any template file declared using @'HtmlImport' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file_

**Comment by appreciated** [comment]
compatibility not is not supported please upgrade you application to npm mode.
