### ISSUE TITLE
Problem generating frontend for Spring Boot-based V14 applications

### ISSUE THREAD

**Issue by markhm** [appreciated/apexcharts-flow#31]
Compliments and many thanks for this wonderful component...!  I have been able to run the examples and started to integrate apexcharts-flow in my application. It looked great and worked well. 

Unfortunately, at a certain moment, I started to experience a strange instability in (the process of preparing) the frontend. At the moment, I am not able to build a working application anymore. 

I have a Spring Boot-based Vaadin application based on: 
    - OpenJDK 13 on macOS 10.15
    - Spring Boot 2.2.0.RELEASE
    - Vaadin 14.0.7
 
I've prepared the following repository to demonstrate the problem: https://github.com/markhm/vaadin_examples

The problem becomes apparent when running: mvn spring-boot:run (or mvn install). The application does not start correctly and shows attached error messages in the browser.

I did note that the apexcharts-flow/pom.xml file excludes META-INF/VAADIN/config/flow-build-info.json. Could this be related? I am unsure unsure how to translate this exclusion element to my Spring Boot-based configuration. 

I would be happy to support troubleshooting and to get apexcharts-flow working under V14 with Spring Boot. Much appreciated. 

Best, Mark

----

<img width="1269" alt="Screenshot 2019-10-19 at 20 35 51" src="https://user-images.githubusercontent.com/1430451/67150170-43615c80-f2b4-11e9-98c9-eaee5c0a933c.png">
<img width="1272" alt="Screenshot 2019-10-19 at 20 36 04" src="https://user-images.githubusercontent.com/1430451/67150168-43615c80-f2b4-11e9-9b4a-10ffbd8666e5.png">

**Comment by appreciated** [comment]
Before getting started with this issue please try [this answer](https://github.com/vaadin/flow/issues/6036#issuecomment-536986765) of an unrelated issue .

**Comment by markhm** [comment]
Thank you for your prompt response. Yes, these steps solved the problem. 🙏🏻

I hope the Vaadin team is aware.

**Comment by appreciated** [comment]
I hope so too! I haven't found a way the reproduce this issue steadily so I haven't reported it yet 🤔.

**Comment by markhm** [comment]
A few similar issues have haunted me in the past. I am thankful that - at least - there is a recipe to solve this.

I had my own approach that - apart from removing target and node_modules - included removing all generated frontend files (package.json, package-lock.json, webpack.config.js and webpack.generated.js), but for some strange reason it did not bring stability. 

Thanks again...!
