### ISSUE TITLE
Line & Area Chart

### ISSUE THREAD

**Issue by maupoc** [appreciated/apexcharts-flow#32]
Hello,

I am looking to create a Chart with Line and Area Series similiar to this demo chart:
https://apexcharts.com/javascript-chart-demos/mixed-charts/line-area/#

I couldn´t find the option (series.type) used in the demo in the official documentation and i didn´t find the option in the API, is it possible at the moment on a different way? 
Any pointers would be appreciated.

Kind regards
Maurice

**Comment by appreciated** [comment]
@maupoc, sorry to disappoint, but this currently not supported.

**Comment by maupoc** [comment]
@appreciated That´s a pity but thank you for your reply.

**Comment by appreciated** [comment]
You are welcome to make a PR though. I'll gladly help you if you want to 🙂

**Comment by maupoc** [comment]
I already saw that and also thinking about it, but i am quite busy at the moment.
Maybe i come back to the offer in the evening but i can´t promis anything yet.

**Comment by maupoc** [comment]
Just to let you know, i am now working on the issue.
I let you know if i need any help.

**Comment by appreciated** [comment]
nice 🙂! If you need any help let me know.
