### ISSUE TITLE
The project does not see the apexcharts-wrapper-styles.css file at startup

### ISSUE THREAD

**Issue by SantAleks** [appreciated/apexcharts-flow#41]
Hello, Johannes. 
My project worked on Vaadin v14.0.10 in compatibilityMode and with ApexCharts v0.9.0. Recently, I turned off the compatibilityMode, changed Vaadin to version 14.1.1, rebuilt the project (moved .css and .js to folder 'frontend'), and changed the ApexCharts to version 2.0.0.b7. As a result, in the IDEA my project starts up and works perfectly. However, if I build the war-package (or jar-package) in the gradle and run it, then at the time of launch the program produces an error:
```
ERROR 2238 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class [com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener]

java.lang.IllegalStateException: 

....  Failed to find the following css files in the node_modules or /home/cab/Project/browser/build/bootScripts/./frontend directory tree:
      - ./com/github/appreciated/apexcharts/apexcharts-wrapper-styles.css
  Check that they exist or are installed. If you use a custom directory for your resource files instead of the default 'frontend' folder then make sure it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)
        at com.vaadin.flow.server.frontend.AbstractUpdateImports.getCssLines(AbstractUpdateImports.java:213) ~[flow-server-2.1.0.jar!/:2.1.0]
```
I do not use johndevs/gradle-vaadin-plugin. My Gradle-file:
```
plugins {
	id 'org.springframework.boot' version '2.2.0.RELEASE'
	id 'java'
	id 'war'
}

apply plugin: 'io.spring.dependency-management'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'application'
mainClassName = 'com.cherentsov.browser.BrowserApplication'

group = 'com.cherentsov'
version = ''
sourceCompatibility = '11'
targetCompatibility = '11'

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
	maven { url "http://maven.vaadin.com/vaadin-addons" }
	maven { url "https://maven.vaadin.com/vaadin-prereleases" }
}

dependencyManagement {
	imports {
		mavenBom 'com.vaadin:vaadin-bom:14.1.1'
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
		exclude group: 'junit', module: 'junit'
	}
	compile("com.vaadin:vaadin-spring-boot-starter")
	compile group: 'com.google.code.gson', name: 'gson', version: '2.8.5'
	compile group: 'org.springframework.amqp', name: 'spring-rabbit', version: '2.2.0.RELEASE'
	compile group: 'com.vaadin', name: 'vaadin-core', version: '14.1.1'
	compile group: 'com.github.appreciated', name: 'apexcharts', version: '2.0.0.beta7'
	compile group: 'org.postgresql', name: 'postgresql', version: '42.2.6'
}
```
In folder './node_modules/' present folders 'onecolor' and 'apexcharts'.
I tried to avoid the error as follows:
1) put the 'apexcharts-wrapper-styles.css' - file nearby to my war-file. 
2) put the css-file along the './frontend/com/github/appreciated/apexcharts/' path.
However, at startup, the program still does not see this css-file.
What could be the problem or how can this error be avoided?

**Comment by appreciated** [comment]
> I do not use johndevs/gradle-vaadin-plugin. 

Oh bummer, you definitely should, it should do all there things you are doing by hand automatically. 

> However, at startup, the program still does not see this css-file. What could be the problem or how can this error be avoided?

I personally would first check if the mentioned files actually landed in the war by unzipping it and serach in the webapp or the resource folder. 
As a reference how it's properly done download and build the [app-starter](https://vaadin.com/start/latest), and see where the files land here case. 
Then add the resources to the same path. 

As already being said I recommend using the `johndevs/gradle-vaadin-plugin` and not doing this by hand.

**Comment by appreciated** [comment]
[Also you might be happy to hear Vaadin will add gradle support in the future](https://vaadin.com/forum/thread/17830616/tomcat-failed-to-start-springboot-vaadin-14-npm-mode-gradle).

**Comment by appreciated** [comment]
New Vaadin versions should have fixed this issue is it still valid?
