### ISSUE TITLE
Zoom Issue: Cannot read property 'niceMin' of null

### ISSUE THREAD

**Issue by esp70** [appreciated/apexcharts-flow#46]
When enabling zoom using the line chart example, while attempting to zoom an error occurs `Type error: Cannot read property 'niceMin' of null`. This was caused by enabling zoom in the builder (below) and attempting to zoom on the browser.

`ApexCharts lineChart = ApexChartsBuilder.get()
                .withChart(ChartBuilder.get()
                        .withType(Type.line)
                        .withZoom(ZoomBuilder.get()
                                .withEnabled(true)<---
                                .build())
                        .build())...`

![image](https://user-images.githubusercontent.com/17239526/75341971-7e2b6080-5863-11ea-9882-fb8988350813.png)

Using Google, I found that in the ApexCharts github, a similar experience was reported and then it was mentioned that once updated to the latest version of apexcharts.js, it was fixed:

[link](https://github.com/apexcharts/apexcharts.js/issues/971)

I am wondering if it is possible to test with the latest update to see if it does fix it. I am kind of stuck without being able to zoom in the chart.

The issue was found while using chrome on a windows desktop, with Vaadin version 14.1.17, appreciated.apexcharts version 2.0.0.beta7, and jetty:run

**Comment by appreciated** [comment]
Was this fixed by the new version?

**Comment by esp70** [comment]
No, unfortunately, it was not fixed

**Comment by esp70** [comment]
Sorry, I take that back. It looks like it was fixed. I followed a cleaning procedure that you posted here:

[post](https://github.com/appreciated/apexcharts-flow/issues/51)

Rebuilt and everything is fine now.
