### ISSUE TITLE
debug error after updating vaadin 14.1.17

### ISSUE THREAD

**Issue by SamerDiab** [appreciated/apexcharts-flow#47]
when i run mvn clean package -Pproduction -DskipTests command as usual ..

npm install gives this error.

> ERROR in ../node_modules/apexcharts/dist/apexcharts.esm.js?babel-target=es5
> Module build failed (from ../node_modules/babel-loader/lib/index.js):
> TypeError: C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\apexcharts\dist\apexcharts.esm.js: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null
>     at Object.validate (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\types\lib\definitions\utils.js:131:11)
>     at validateField (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\types\lib\validators\validate.js:24:9)
>     at Object.validate (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\types\lib\validators\validate.js:17:3)
>     at NodePath._replaceWith (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\replacement.js:172:7)
>     at NodePath._remove (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\removal.js:55:10)
>     at NodePath.remove (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\removal.js:34:8)
>     at hooks (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\lib\removal-hooks.js:11:12)
>     at NodePath._callRemovalHooks (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\removal.js:46:9)
>     at NodePath.remove (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\removal.js:26:12)
>     at convertFunctionParams (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\plugin-transform-parameters\lib\params.js:88:30)
>     at PluginPass.Function (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\plugin-transform-parameters\lib\index.js:30:53)
>     at newFn (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\visitors.js:179:21)
>     at NodePath._call (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\context.js:55:20)
>     at NodePath.call (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\context.js:42:17)
>     at NodePath.visit (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\context.js:90:31)
>     at TraversalContext.visitQueue (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:112:16)
>     at TraversalContext.visitSingle (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:84:19)
>     at TraversalContext.visit (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:140:19)
>     at Function.traverse.node (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\index.js:84:17)
>     at NodePath.visit (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\context.js:97:18)
>     at TraversalContext.visitQueue (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:112:16)
>     at TraversalContext.visitMultiple (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:79:17)
>     at TraversalContext.visit (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:138:19)
>     at Function.traverse.node (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\index.js:84:17)
>     at NodePath.visit (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\context.js:97:18)
>     at TraversalContext.visitQueue (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:112:16)
>     at TraversalContext.visitMultiple (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:79:17)
>     at TraversalContext.visit (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:138:19)
>     at Function.traverse.node (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\index.js:84:17)
>     at NodePath.visit (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\context.js:97:18)
>     at TraversalContext.visitQueue (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:112:16)
>     at TraversalContext.visitMultiple (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:79:17)
>     at TraversalContext.visit (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:138:19)
>     at Function.traverse.node (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\index.js:84:17)
>     at NodePath.visit (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\path\context.js:97:18)
>     at TraversalContext.visitQueue (C:\Users\UmitKIRTIL\IdeaProjects\yoksismezunaktarimiv2\node_modules\@babel\traverse\lib\context.js:112:16)
>  @ ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es5 22:0-36 42:32-42
>  @ ../target/frontend/generated-flow-imports.js?babel-target=es5
> Any ideas ?

**Comment by appreciated** [comment]
[Have you treid the following?](https://github.com/appreciated/apexcharts-flow/issues/31#issuecomment-544201927)

**Comment by SamerDiab** [comment]
Yes, off course. If affected all of our production builds :/, where we use CI and every time we rebuild from scratch.

**Comment by appreciated** [comment]
Which version of apexcharts is this?

**Comment by SamerDiab** [comment]
2.0.0.beta7 with vaadin updated to 14.1.18, it was working fine with 14.0.1, btw, thank you for this amazing port!

**Comment by appreciated** [comment]
So I think I got it. Webpack seems fail on minifying the apexcharts dependency.
Good news is, this issue is not related to this addon. Bad news is I cannot really do much to fix this. 
I will check if updating to a newer version fixes this issue.

**Comment by razbensimon** [comment]
> So I think I got it. Webpack seems fail on minifying the apexcharts dependency (after downgrading it to es5).
> Good news is, this issue is not related to this addon. Bad news is I cannot really do much to fix this.
> I will check if updating to a newer version fixes this issue.

have the same issue, waiting to see if you resolved it :)

**Comment by umitkirtil** [comment]
> So I think I got it. Webpack seems fail on minifying the apexcharts dependency (after downgrading it to es5).
> Good news is, this issue is not related to this addon. Bad news is I cannot really do much to fix this.
> I will check if updating to a newer version fixes this issue.

so i relates to ApexCharts.js itself ?

**Comment by appreciated** [comment]
> have the same issue, waiting to see if you resolved it :)

Newer version didn't fix it. So there is nothing I can do right now.

Since I am very short on time (doing my thesis currently), I cannot put in the hours currenlty. 

I see two possiblities:
- [You may be able to disable the optimization via maven](https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-advanced.html#goal-parameters-2).
- Or you need to downgrade to a lower Vaadin version to "fix" this issue.

**Comment by appreciated** [comment]
> so it relates to ApexCharts.js itself ?

- Maybe, I am not an expert with webpack. 
- It could also possibly be that the minifying option that the [maven-plugin](https://github.com/vaadin/maven-plugin) uses by default, is too "strict", and is not compatible with a lot of the npm dependencies.
- Also it could be a bug in the current version of the babel minifier which is used by the maven-plugin. 
Since I haven't done any investigation into that direction, and I don't have a reliable opinion on this matter.

**Comment by camilaraldi** [comment]
Hi, I have the same issue.

**Comment by SamerDiab** [comment]
We are taking time to investigate, i hope we find a fix soon. I think it might be an issue related to ES6.

**Comment by creslinux** [comment]
I have the same issue. 
Our FE is building into a docker for some 6 months, today we can only build if include an archived package-lock.json. A clean install fall foul of the same. Our error is 

```
npm info it worked if it ends with ok
npm info using npm@6.4.1
npm info using node@v8.16.2
npm info lifecycle maturity-model@0.1.0~prebuild: maturity-model@0.1.0
npm info lifecycle maturity-model@0.1.0~build: maturity-model@0.1.0

> maturity-model@0.1.0 build /usr/src/app
> react-scripts --max-http-header-size=60000 build

Creating an optimized production build...
Failed to compile.

./node_modules/apexcharts/dist/apexcharts.common.js
TypeError: /usr/src/app/node_modules/apexcharts/dist/apexcharts.common.js: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null


npm info lifecycle maturity-model@0.1.0~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! maturity-model@0.1.0 build: `react-scripts --max-http-header-size=60000 build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the maturity-model@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 47881ms
```

**Comment by creslinux** [comment]
For additional info, this container is built several times / day, so the change should be in the last 24 hours.

**Comment by austinbachman** [comment]
Same issue here running `yarn build`

```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./node_modules/apexcharts/dist/apexcharts.common.js
TypeError: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null
```

**Comment by creslinux** [comment]
@SamerDiab we are only on ES6, our build never on 5. The ES5 or 6 may be a red herring

**Comment by creslinux** [comment]
First let me say **I am not a Front End Developer and Do NOT know JS or React**  

My builds are now working if I add the following into my package.json
```
     "@babel/core": "^7.8.7"
    "yaml": "^1.7.2"
```

**Comment by junedchhipa** [comment]
I have released **apexcharts@3.16.1** to fix the `Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null` issue.

Please upgrade to the latest version and update this thread if **[3.16.1](https://www.npmjs.com/package/apexcharts)** works for you.

**Comment by creslinux** [comment]
3.16.1 built cleanly for me without manually adding deps into package.json

Thanks @junedchhipa

**Comment by camilaraldi** [comment]
Thanks @junedchhipa

**Comment by appreciated** [comment]
Updating to the new version also resolved the issue. Thanks @junedchhipa 🙏 for the prompt fix!

**Comment by dougfabris** [comment]
@junedchhipa Thaaaank you for the fix!
