### ISSUE TITLE
Does not work in Vaadin Flow 15.0.0

### ISSUE THREAD

**Issue by ugurdoksan** [appreciated/apexcharts-flow#48]
The latest version of this library does not work on V15

**Comment by appreciated** [comment]
What isn't working?

**Comment by ugurdoksan** [comment]
DemoView example does not work. Shows only blank screen.

Tomcat Version: 9.0
Java Version: 11

**Not:** 
I am using your **apexchart add-on** and **color-picker-field add-on** in _Vaadin 14 NPM Mode successfully._ 
I just upgraded my working Vaadin 14 project to Vaadin 15. 
All I do is changing Vaadin version, after that your add-ons not working.

**Comment by ugurdoksan** [comment]
Here is the other issue I've created for color-picker-field add-on:

https://github.com/Juchar/color-picker-field/issues/7

**Comment by appreciated** [comment]
Well, I must say I'm not suprised, I hope you don't think that it is my fault that isn't working again. Maybe you could file a complaint on the offical flow repository that some unoffical addons could make it into the offical test builds.

Any error in the console?

**Comment by ugurdoksan** [comment]
Shows this error for color-picker-field addon.

**Couldn't find the definition of the element with tag 'color-picker-field' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file**

Does not show any error for apexcharts add on.

![Capture](https://user-images.githubusercontent.com/24225109/76010778-87cc5c80-5f24-11ea-9943-e7a421eb923b.PNG)

**Comment by appreciated** [comment]
Hmm I will post an issue on the offical repository.

**Comment by ugurdoksan** [comment]
1. I built my project(color-picker-field add-on) with maven-jetty-plugin
2. Produced exploded war file via it
3. Copied that war file under Tomcat

Boom! It's working.

But when I replace maven-jetty-plugin with maven-war-plugin, this scenario does NOT work.

**Comment by ugurdoksan** [comment]
@appreciated 
The link below solves the issue without Vaadin Team's upgrade.

https://github.com/Gubancs/leaflet4vaadin/commit/616c6fd0299f2519f5b83e4c15b9689e2504e3b3

Gubancs solved the same issue and released the new version of the project.

**Comment by appreciated** [comment]
Vaadin 15.0.3 should fix this issue.
