### ISSUE TITLE
Module not found: Error: Can't resolve 'apexcharts?babel-target=es5

### ISSUE THREAD

**Issue by rucko24** [appreciated/apexcharts-flow#50]
**Describe the bug**
the code does not allow to make a complete deploy in the application, all in compilation time throws this error, Just create the graph, everything worked, only when I upgraded to version 2.0.0.beta8, Now for my application to work, I must not instantiate any ApexChart, neither version 2.0.0.beta7 nor 2.0.0.beta8 , **unfortunate**, because before everything worked wonderfully great addon

**Steps or code example to Reproduce**
1. Go to At compile time
2. Click on At compile time
3. Scroll down to At compile time

ERROR in ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es5
Module not found: Error: Can't resolve 'apexcharts?babel-target=es5' in 'C:\Users\Rubn\IdeaProjects\calc4tupincho\node_modules\@vaadin\flow-frontend\com\github\appreciated\apexcharts'
 @ ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es5 22:0-36 44:32-42
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5
ERROR in ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es6
Module not found: Error: Can't resolve 'apexcharts?babel-target=es6' in 'C:\Users\Rubn\IdeaProjects\calc4tupincho\node_modules\@vaadin\flow-frontend\com\github\appreciated\apexcharts'
 @ ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es6 4:0-36 126:30-40
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6
ERROR in ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es5
Module not found: Error: Can't resolve 'onecolor?babel-target=es5' in 'C:\Users\Rubn\IdeaProjects\calc4tupincho\node_modules\@vaadin\flow-frontend\com\github\appreciated\apexcharts'
 @ ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es5 40:19-38
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5
ERROR in ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es6
Module not found: Error: Can't resolve 'onecolor?babel-target=es6' in 'C:\Users\Rubn\IdeaProjects\calc4tupincho\node_modules\@vaadin\flow-frontend\com\github\appreciated\apexcharts'
 @ ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es6 122:17-36
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6
ERROR in build/vaadin-bundle-6ef0cb11cf339d15e2e8.cache.js from Terser
Unexpected token: operator (!) [build/vaadin-bundle-6ef0cb11cf339d15e2e8.cache.js:9508,30]
ERROR in build/vaadin-bundle.es5-8437b79c92e96859727e.cache.js from Terser
Unexpected token: operator (!) [build/vaadin-bundle.es5-8437b79c92e96859727e.cache.js:9994,32]

**or if the bug occurs when using a specific chart type**
```
  final ApexCharts pieChart = ApexChartsBuilder.get()
                .withChart(ChartBuilder.get()
                        .withType(Type.radialBar)//**bug with donut, and other**
                        .build())
                .withSeries(bodyFat,masaGrasa,masaLimpia)
                .build();
```

**Expected behavior**
Just create the graph, everything worked, only when I upgraded to version 2.0.0.beta8

**Screenshots**

![ApexCharError](https://user-images.githubusercontent.com/17187599/76701160-dfa25a80-66be-11ea-872f-62272cc39bc7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64bits
 - Browser NONE
 - Version NONE

**Smartphone (please complete the following information):**
 - Device: NONE
 - OS: NONE
 - Browser NONE
 - Version NONE

**Additional context**
Vaadin flow 14.0.13
Springboot 2.1.7.RELEASE
app-layout-addon 4.0.0.rc5

**Comment by appreciated** [comment]
[Have you tried the following?](https://github.com/vaadin/flow/issues/6036#issuecomment-536986765)

**Comment by rucko24** [comment]
Thanks a lot, that` correct, maybe cache these file. please close this issue.

**Comment by appreciated** [comment]
Since this issue occured already so often to many users I came up with the following Maven configuration:
```
<plugin>
    <artifactId>maven-clean-plugin</artifactId>
    <version>3.1.0</version>
    <configuration>
        <filesets>
            <fileset>
                <directory>.</directory>
                <includes>
                    <include>package.json</include>
                    <include>package-lock.json</include>
                    <include>webpack.config.js</include>
                    <include>webpack.generated.js</include>
                </includes>
                <followSymlinks>false</followSymlinks>
            </fileset>
            <fileset>
                <directory>./node_modules</directory>
                <includes>
                    <include>**/**</include>
                </includes>
                <followSymlinks>false</followSymlinks>
            </fileset>
        </filesets>
    </configuration>
</plugin>
```

To resolve the issue with this `mvn clean install`
