### ISSUE TITLE
Couldn't find the definition of the element with tag 'apex-charts-wrapper' in any template file declared using '@JsModule' annotations.

### ISSUE THREAD

**Issue by umitkirtil** [appreciated/apexcharts-flow#51]
Hi ,

Vaadin 14.1.20 and apexcharts - beta8 versions...

**development mode gives this error :** Couldn't find the definition of the element with tag 'apex-charts-wrapper' in any template file declared using '@JsModule' annotations.

production mode : just blank page with some js error. i added ss for it.

i did these steps as usual ... 

> I was able to fix this issue by removing:
> 
> target
> node_modules
> package-lock.json
> Then I followed it up by a clean install -> Issue solved.
> 
> I think this has to do with an old version of @vaadin/vaadin-grid in the package-lock.json
> which is for some reason not updated by the vaadin-maven-plugin.
> This causes the webpack to fail since it uses an older version of @vaadin/vaadin-grid for complication then required.
> 
> 
> mvn clean install -DskipTests
> mvn clean package -Pproduction -DskipTests
> mvn spring-boot:run

Anyone else having these problem ?

[Debug Mode Error](https://ibb.co/jhysK4w)
[Production Mode Error](https://ibb.co/9rd8y0b)

Best regards Umit.

**Comment by appreciated** [comment]
Try doing a `mvn clean install` and start the application as usual using with the following plugin:
```
 <plugin>
    <artifactId>maven-clean-plugin</artifactId>
    <version>3.1.0</version>
    <configuration>
        <filesets>
            <fileset>
                <directory>.</directory>
                <includes>
                    <include>package.json</include>
                    <include>package-lock.json</include>
                    <include>webpack.config.js</include>
                    <include>webpack.generated.js</include>
                </includes>
                <followSymlinks>false</followSymlinks>
            </fileset>
            <fileset>
                <directory>./node_modules</directory>
                <includes>
                    <include>**/**</include>
                </includes>
                <followSymlinks>false</followSymlinks>
            </fileset>
        </filesets>
    </configuration>
</plugin>
```
I just tried it with a fresh setup project, works for me.

**Comment by mvdberge** [comment]
I've got the exact same issue. I tried different vaadin versions (up to 14.2.0.alpha9) and am using apexcharts 2.0.0.beta9. I deleted all temporaty files, including node and node_modules etc. 
Anything I could try or help to find the source of the bug?

**Comment by appreciated** [comment]
If you have already tried the solution above, and it still does not work it might be the [following issue (I hope not so)](https://github.com/vaadin/flow/issues/7752)

**Comment by mvdberge** [comment]
Yes, I tried the solution above, doesn't help. 
What I found out is that in development mode, when the frontend is built on startup of the application, everything is fine. Only the production mode doesn't work, although most frontend components seem to be built fine as I see a partial working application.

**Comment by umitkirtil** [comment]
Hi New Update on This Issue ..

@appreciated  Have you tried your wrapper with spring security ? .. i believe ss blocking js modules .. 

i tried to allow it like this ..

`@Override
    public void configure(WebSecurity web) {
        web.ignoring().antMatchers(
                // Vaadin Flow static resources
                "/VAADIN/**",

                // the standard favicon URI
                "/favicon.ico",

                // the robots exclusion standard
                "/robots.txt",

                // web application manifest
                "/manifest.webmanifest",
                "/sw.js",
                "/offline-page.html",

                // icons and images
                "/icons/**",
                "/images/**",

                // (development mode) static resources
                "/frontend/**",// (development mode) static resources
                "/node_modules/**",

                // (development mode) webjars
                "/webjars/**",

                // (development mode) H2 debugging console
                "/h2-console/**",

                // (production mode) static resources
                "/frontend-es5/**", "/frontend-es6/**");
    }`

this didnt help. without spring security it works fine. but when i try to use this wrapper it keeps giving this error. 

i beleive you can produce this error with vaadin's official full stack app starter as well. hope this issue get fixed.

**Comment by umitkirtil** [comment]
Final comment ... setting vaadin.whitelisted-packages in application.properties file cousing this error. Because of this line on your prop file cousing not to install npm modules ... the only strange thing is why is affecting only apex-chart-wrapper ? i use several more add-ons... anyways you may close this issue for good :).

again thanks for this great add-on. have a good (healty) day.

**Comment by appreciated** [comment]
I'm glad you managed to figure it out. Sorry that I cannot be a great help currently. You should definitely consider opening an issue on [vaadin-spring](https://github.com/vaadin/spring/issues) about this. This shouldn't be necessary.

**Comment by vilmosnagy** [comment]
@appreciated It seems to me that this happens 'cause there's an extra dot (`.`) in the `JSModule` annotation.

Using Vaadin 14.4.5, at the `BundleParser.java:271` I see the following:

![image](https://user-images.githubusercontent.com/6528869/103414595-e7b08580-4b7e-11eb-9f4f-b8bdb15f2510.png)

If the value in the annotation would be `com/github/appreciated/apexcharts/apexcharts-wrapper.js` then the condition would match, but in this case the extra dot does not match the file's path.

I'm using Gradle and Vaadin 14.4.5 with Spring Boot.

**Comment by appreciated** [comment]
@vilmosnagy Thank you for providing this information, it seems that this is a Vaadin(-Spring) Issue. [As the offical documentation shows](https://vaadin.com/docs/flow/importing-dependencies/tutorial-ways-of-importing.html) adding a "." at the beginning of paths is the way to when working with paths in addons. 
Please head to [Vaadin Spring](https://github.com/vaadin/spring) to report this issue.
