### ISSUE TITLE
Download is not working

### ISSUE THREAD

**Issue by frostyaxe** [appreciated/apexcharts-flow#64]
I am trying to download the chart in PNG but it is not working. When I executed it in the debug mode then I saw the below error:

apexcharts.esm.js?39df:6 Uncaught (in promise) TypeError: e.setAttribute is not a function
    at t.value (apexcharts.esm.js?39df:6)
    at eval (apexcharts.esm.js?39df:6)
    at new Promise (<anonymous>)
    at t.value (apexcharts.esm.js?39df:6)
    at t.value (apexcharts.esm.js?39df:6)
    at t.value (apexcharts.esm.js?39df:6)
value @ apexcharts.esm.js?39df:6
eval @ apexcharts.esm.js?39df:6
value @ apexcharts.esm.js?39df:6
value @ apexcharts.esm.js?39df:6
value @ apexcharts.esm.js?39df:6
Promise.then (async)
value @ apexcharts.esm.js?39df:6
value @ apexcharts.esm.js?39df:6

**Comment by appreciated** [comment]
Which Vaadin/Apexcharts-Flow version are you using?
[Is the download in the addon demo working for you?](https://appreciated-collection.herokuapp.com/apexcharts/)

**Comment by NikoMart** [comment]
3.18.0 - ok
3.18.1 - download is not working

**Comment by frostyaxe** [comment]
> re you using?
I am using the below version right now :)
2.0.0.beta9

**Comment by frostyaxe** [comment]
> 3.18.0 - ok
> 3.18.1 - download is not working

Vaadin Add-on of the aforementioned version is not present in the directory. :)

**Comment by PriyadharshiniBalavadivel** [comment]
Hi @appreciated ,

Could you please share if there is any update on this issue. We are facing the same issue in version 2.0.0.beta9(Vaadin version :14.3.3) . **Download SVG** results in the above error, **Download PNG** does nothing.

**Comment by appreciated** [comment]
[This issue is fixed in the new version](https://vaadin.com/directory/component/apexchartsjs/2.0.0.beta10)

**Comment by srikanthdevasani** [comment]
apexcharts download csv, png,svg not working in mobile app
