### ISSUE TITLE
how to work with Serie ?

### ISSUE THREAD

**Issue by fred-parret** [appreciated/apexcharts-flow#68]
In all examples, linechart example, to set Serie of data is .withSeries(new Series<>("String", new double[]{11,55}], new double[]{12,5}], new double[]{13,48}], etc ...)
So, I would like to add and replace data with Array [][] and add it ? In example, 
.withSeries(new Series<>("String", Array[][]))
How I can made it ?
Frederic

**Comment by appreciated** [comment]
[Have you checked out the code in the demo?](https://appreciated-collection.herokuapp.com/apexcharts/)

**Comment by appreciated** [comment]
What does your Data represent?
```
.withSeries(new Series<>("String", new double[]{11,55}], new double[]{12,5}], new double[]{13,48}], etc ...)
```
Do you want to have two lines? Or is it the X and the Y value?

**Comment by fred-parret** [comment]
It's X and Y value.

**Comment by appreciated** [comment]
The Series must only contain the Y Values.

**Comment by appreciated** [comment]
[If you checkout the offical missing data example things might get clearer](https://apexcharts.com/javascript-chart-demos/line-charts/null-values/)

**Comment by fred-parret** [comment]
No, Sorry, with this example, .withSeries(new Series<>("String", new double[]{11,55}], new double[]{12,5}], new double[]{13,48}], etc ...) each double[] represents X and Y values.

**Comment by appreciated** [comment]
> No, Sorry, with this example, .withSeries(new Series<>("String", new double[]{11,55}], new double[]{12,5}], new double[]{13,48}], etc ...) each double[] represents X and Y values.

I understand that, And I am pretty sure that Apexchats won't accept it. You need to split your Data into two seperate Arrays one containing the X values and one containing the Y values. The Y Values go into the series and the X values need to be passed as labels.

**Comment by fred-parret** [comment]
Yes, I do that. I use DataLabels, but not Label. I don't know differences between 2 ?

**Comment by appreciated** [comment]
The offical documentation might clear that up [DataLabels](https://apexcharts.com/docs/datalabels/) and [Series](https://apexcharts.com/docs/series/)
