### ISSUE TITLE
Problem with filling slices by colors in ApexChart

### ISSUE THREAD

**Issue by marcinfelskowski** [appreciated/apexcharts-flow#70]
Hi.

I have such a issue.
I don't receive the colors on apex chart type: donut - on slices after runing such java code:
----------------------------------------------Java Code (Vaadin14)----------------------------
```
Double[] series = new Double[] {12.34, 56.78, 90.12, 34.56, 78.90};
String[] colors = new String[] {"red", "black", "purple", "grey", "green"};
String[] labels = new String[] {"Label_1", "Label_2", "Label_3", "Label_4", "Label_5"};

Fill fill = new Fill();

fill.setColors(Arrays.asList(colors));

ApexCharts donutChart = ApexChartsBuilder.get()
				.withChart(ChartBuilder.get().withType(Type.donut)
						.build())
				.withFill(fill)
				.withLabels(labels)
				.withColors(colors)
				.withSeries(series)
				.build();
```
------------------------------------------------------------------------------------------------
Doesn't work correctly  part: .withFill.
Others parts works ok.
What I'm doing wrong?

![donut_without_slice_filling_colors](https://user-images.githubusercontent.com/19687735/82345691-d6eb3f00-99f5-11ea-9418-63fe74f8f565.jpg)

**Comment by appreciated** [comment]
I guess this issue is releated to #44 or maybe #61

**Comment by marcinfelskowski** [comment]
Yeap, maybe related - they have problems with colors too - in other parts of charts or it functionalities. But there is solution? We are  waiting for bug solving or have too use *.js not *.java?

**Comment by appreciated** [comment]
I'm currently busy doing my thesis. I hope you understand that I cannot put in the hours currently. It will be over by the end of next month. But this does not mean that this cannot be done by using this addon. The Code is not complicated, you could provide a PR to solve this issue.

**Comment by marcinfelskowski** [comment]
Hi. Thanks for the answer. I understand that. It is great what You do it and share with that for the others :) like me. At this moment i do this on the original blue colors. I will wait for the solution to the end next month from You. If i can I will look to the code, maybe with my friend - i don't have expierience with javascript - and solve it.

**Comment by marcinfelskowski** [comment]
It is posibble to make methods in javaCode:
ChartBuilder.get()
                        .withType(Type.bar)
                        .withHeight("500") <- right now are they in px? can be also in rem?
                        .withWidth("1200") <- right now are they in px? can be also in rem?
                        .build()

**Comment by appreciated** [comment]
This is not decided by this addon but by the offical code.
[Documentation - Height](https://apexcharts.com/docs/options/chart/height/)
[Documentation - Width](https://apexcharts.com/docs/options/chart/width/)
Try it out maybe it works.

**Comment by marcinfelskowski** [comment]
If I give x% so it will be responsive and will resize to the size of screen?

**Comment by appreciated** [comment]
Well try it out I don't know 🙈

**Comment by appreciated** [comment]
@marcinfelskowski 
I finally had time to check your code the issue is that apexcharts does not support colors as name only in hex or rgb/rgba format.

If you correct your example accordingly it works as exspected:
```
Double[] series = new Double[]{12.34, 56.78, 90.12, 34.56, 78.90};
String[] colors = new String[]{"#ff0000", "#000000", "#00ffff", "#aaaaaa", "#00ff00"};
String[] labels = new String[]{"Label_1", "Label_2", "Label_3", "Label_4", "Label_5"};

Fill fill = new Fill();

fill.setColors(Arrays.asList(colors));

ApexCharts donutChart = ApexChartsBuilder.get()
        .withChart(ChartBuilder.get().withType(Type.donut)
                .build())
        .withFill(fill)
        .withLabels(labels)
        .withColors(colors)
        .withSeries(series)
        .build();
donutChart.setWidth("300px");
add(donutChart);
```

**Comment by marcinfelskowski** [comment]
Hi,

adding colors at that way:
String[] colors = new String[]{"#ff0000", "#000000", "#00ffff", "#aaaaaa", "#00ff00"};
working good 👍 

thanks :)
Marcin
