### ISSUE TITLE
Wrong order of days of month in timeline

### ISSUE THREAD

**Issue by code-6** [appreciated/apexcharts-flow#75]
**Describe the bug**
Timeline on chart displays wrong order of days of month. For example first going 19 march then 02 march.

**Steps or code example to Reproduce**
1. Go to 'https://apexcharts.com/angular-chart-demos/timeline-charts/distributed/' or 'https://apexcharts.com/angular-chart-demos/timeline-charts/advanced/'
4. See example timeline

With vaadin java it also same. See code and screenshots of result. 
```@Route(value = "apex", layout = MainLayout.class)
public class TestApexCharts extends Div {
    DateCoordinate[] list;
    List<Tour> tours;


    private TourService tourService;

    public TestApexCharts(TourService tourService) {
        this.tourService = tourService;

        tours = tourService.getByMonthAndYear(DateTime.now().getMonthOfYear(), 2020);
        ApexCharts barChart = ApexChartsBuilder.get()
                .withChart(ChartBuilder.get()
                        .withType(Type.rangeBar)
                        .build())
                .withPlotOptions(PlotOptionsBuilder.get()
                        .withBar(BarBuilder.get()
                                .withHorizontal(true)
                                .build())
                        .build())
                .withDataLabels(DataLabelsBuilder.get()
                        .withEnabled(false)
                        .build())
                .withSeries(getSeries())
                .withYaxis(YAxisBuilder.get()
                        .withMin(LocalDate.of(2020, DateTime.now().getMonthOfYear(), 1))
                        .withMax(LocalDate.of(2020, DateTime.now().getMonthOfYear(), DateTime.now().dayOfMonth().getMaximumValue()))
                        .build())
                .withXaxis(XAxisBuilder.get()
                        .withType(XAxisType.datetime)
                        .build())
                .build();
        barChart.setWidth("1000px");
        barChart.setHeight("500px");
        add(barChart);
        setSizeFull();
    }

    private Series<DateCoordinate> getSeries(){
        list = new DateCoordinate[tours.size()];
        AtomicInteger i = new AtomicInteger();
        tours.forEach(t->{
            list[i.get()] = new DateCoordinate<>(t.getTitle(), joda2java(t.getFrom()), joda2java(t.getTo()));
            i.getAndIncrement();
        });
        Series<DateCoordinate> s = new Series<>();
        s.setData(list);
        return s;
    }

    private LocalDate joda2java(DateTime date){
        return LocalDate.of(date.getYear(), date.getMonthOfYear(), date.getDayOfMonth());
    }
}
```

**Expected behavior**
Expected right order of days of month

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 LTS
 - Browser chrome

![Снимок экрана от 2020-08-09 18-59-01](https://user-images.githubusercontent.com/46374696/89732811-06e53400-da73-11ea-88cf-f7d77177dacf.png)
![Снимок экрана от 2020-08-09 18-47-05](https://user-images.githubusercontent.com/46374696/89732817-09e02480-da73-11ea-8933-603f287b83b0.png)
![Снимок экрана от 2020-08-09 19-03-55](https://user-images.githubusercontent.com/46374696/89732822-18c6d700-da73-11ea-8bb2-d2f8be7a7de5.png)

**Comment by appreciated** [comment]
@code-6 This addon is a wrapper of the official library. Only post issues where the behavior of the wrapper differs from the official library. If the official library has a wrong behavior you should open an issue [on its repository](https://github.com/apexcharts/apexcharts.js).
