### ISSUE TITLE
How to set manually step of iteration between max and min values on timeline chart?

### ISSUE THREAD

**Issue by code-6** [appreciated/apexcharts-flow#76]
There is a Feature to set min and max values for axis (eg. timeline), but then addon automatically sets the step, for example if min = 1 and max = 10 then axis will be like this 1, 3, 6, 9. How to contorll this manually? What if i want to display each value  in a range? Example 1,2,3,4,5 ... till max. I don't found how to do that. 

In my case I have month where min = 1 and max = 28, 29, 30 or 31, and i want to display each day on a timeline axis. For example 01 march, 02 march, 03 march, 04 march ... etc. I want have possibility to manual control step of iteration. Also will be good to have possibility to control what to display, i mean what if month name i will display on a title of chart, but for a days numbers i want to have also days of week. for example 1 mon, 2 tue, 3 wed, 4 thu ... etc. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by appreciated** [comment]
@code-6 Have you checked the official library if it offers a solution for this?

**Comment by code-6** [comment]
> @code-6 Have you checked the official library if it offers a solution for this?

@appreciated Hello! No, I don't checked this. I thought this is right place to ask. I'll create an issue on official library as well. Thank you for your reply!
