### ISSUE TITLE
Warning: "export 'default' (imported as 'ApexCharts') was not found in 'apexcharts'

### ISSUE THREAD

**Issue by DanielMartensson** [appreciated/apexcharts-flow#83]
**Describe the bug**
This is just a warning when I compile Vaadin with ApexCharts.

**Steps or code example to Reproduce**

Got to https://github.com/DanielMartensson/OpenSourceLogger and create a JAR file with the Maven Command:

`mvn package -Pproduction`

Before the JAR file have been built, you will see this inside the terminal.

```
WARNING in ../node_modules/@vaadin/flow-frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js?babel-target=es5 48:32-42                                                                                                                        
"export 'default' (imported as 'ApexCharts') was not found in 'apexcharts'                                                   
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 
```
I don't if it affecting the charts. Everything seems to work. But I just got that warning.

**Software**
Vaadin 14.3.3
ApexCharts: 2.0.0.beta10

**Comment by appreciated** [comment]
@DanielMartensson thanks for reporting. It seems that the ApexCharts import in `apexcharts-wrapper.js` is not correctly resolved by Vaadin. I will try to change the import from `import ApexCharts from 'apexcharts'` to `import ApexCharts from 'apexcharts/dist/apexcharts.esm'`, it might resolve the warning.
