### ISSUE TITLE
The Demo code example for PieChart has a Problem.

### ISSUE THREAD

**Issue by tedca77** [appreciated/apexcharts-flow#87]
When copying and pasting the example from the demo page, the withLegend option is not supported by OptionsBuilder 

 .withOptions(OptionsBuilder.get()
                                **.withLegend**(LegendBuilder.get().
                                        .withPosition(Position.bottom)
                                        .build())
                                .build())
                        .build())

I am new to using ApexCharts,, so apologies if this is incorrect.

**Comment by appreciated** [comment]
It seems that the code you copied does not match with example given [online](https://appreciated-collection.herokuapp.com/apexcharts/):
```
public class PieChartExample extends Div {
    public PieChartExample() {
        ApexCharts pieChart = ApexChartsBuilder.get()
                .withChart(ChartBuilder.get().withType(Type.pie).build())
                .withLabels("Team A", "Team B", "Team C", "Team D", "Team E")
                .withLegend(LegendBuilder.get()
                        .withPosition(Position.right)
                        .build())
                .withSeries(44.0, 55.0, 13.0, 43.0, 22.0)
                .withResponsive(ResponsiveBuilder.get()
                        .withBreakpoint(480.0)
                        .withOptions(OptionsBuilder.get()
                                .withLegend(LegendBuilder.get()
                                        .withPosition(Position.bottom)
                                        .build())
                                .build())
                        .build())
                .build();
        add(pieChart);
        setWidth("100%");
    }
}
```
Please try to copy the code again.

**Comment by tedca77** [comment]
![apex legend](https://user-images.githubusercontent.com/5850813/102604356-f5e0b980-411b-11eb-98ef-228940d55ec1.png)
Hi there - I tried again copying the example using IntelliJ and Vaadin 14 and 2.0.0.beta10 of ApexCharts.

**Comment by appreciated** [comment]
May I see the `ResponseBuilder` import?

**Comment by tedca77** [comment]
I see the issue, I was using the incorrect import:
import com.github.appreciated.apexcharts.config.locale.builder.OptionsBuilder;
rather than :
import com.github.appreciated.apexcharts.config.responsive.builder.OptionsBuilder;
Apologies.

**Comment by appreciated** [comment]
@tedca77 thank you for clarifying.
