### ISSUE TITLE
Chart -> chart.setLocale -> withOptions -> ToolbarBuilderget.get().withExportToCSV ... where it is? :)

### ISSUE THREAD

**Issue by marcinfelskowski** [appreciated/apexcharts-flow#88]
Hi,

I have a ApexCharts version for Java (apexcharts-2.0.0.beta10.jar).

I create a chart:
Chart chart = ChartBuilder.get()....build();
chart.setLocales(locale);
Locale locale = LocaleBuilder.get()... withOptions(option)bulild();
Options options = OptionsBuilder.get()...withToolbar(toolbar).build();
Toolbar toolbar = ToolbarBuilder.get().withExportToPNG("...")
.withExportToSVG("...").build();

I find, that is posibility to set the name of label for ToolbarBuilder.get().withExportToPNG(...).withExportToSVG(...) but there isn't a posibilty to set .withExportToCSV

1 ask:
Is this method possible to get in next versions or is a bug that there is no such method or it is private or protected but not public?
2 ask:
I can send you locale for 'pl' (Poland). Is possible to add this to locales package?

:)
Marcin

**Comment by appreciated** [comment]
@marcinfelskowski Pull requests are always welcome. I guess the mentioned method was missing in the [type script definition of apexcharts](https://github.com/apexcharts/apexcharts.js/blob/master/types/apexcharts.d.ts) from which this wrapper was transpiled from.

**Comment by marcinfelskowski** [comment]
pl.json example to pull

{
  "name": "pl",
  "options": {
    "months": [
      "Styczeń",
      "Luty",
      "Marzec",
      "Kwiecień",
      "Maj",
      "Czerwiec",
      "Lipiec",
      "Sierpień",
      "Wrzesień",
      "Październik",
      "Listopad",
      "Grudzień"
    ],
    "shortMonths": [
      "Sty",
      "Lut",
      "Mar",
      "Kwi",
      "Maj",
      "Cze",
      "Lip",
      "Sie",
      "Wrz",
      "Paź",
      "Lis",
      "Gru"
    ],
    "days": [
      "Niedziela",
      "Poniedziałek",
      "Wtorek",
      "Środa",
      "Czwartek",
      "Piątek",
      "Sobota"
    ],
    "shortDays": ["Nd", "Pn", "Wt", "Śr", "Cz", "Pt", "Sb"],
    "toolbar": {
      "exportToSVG": "Pobierz SVG",
      "exportToPNG": "Pobierz PNG",
      "exportToCSV": "Pobierz CSV",
      "menu": "Menu",
      "selection": "Wybieranie",
      "selectionZoom": "Zoom: Wybieranie",
      "zoomIn": "Zoom: Przybliż",
      "zoomOut": "Zoom: Oddal",
      "pan": "Przesuwanie",
      "reset": "Resetuj"
    }
  }
}

**Comment by marcinfelskowski** [comment]
I created the pull request but... i had made a wrong file name (pj.json, should be pl.json). Can You fix it? :)

**Comment by marcinfelskowski** [comment]
I create a pull request:
https://github.com/appreciated/apexcharts-flow/pull/95

**Comment by marcinfelskowski** [comment]
I created the issue/bug there:
https://github.com/apexcharts/apexcharts.js/issues/2121
