### ISSUE TITLE
ApexChartsBuilder should accept multiple Y axis like corresponding JavaScript API

### ISSUE THREAD

**Issue by Obi-TP** [appreciated/apexcharts-flow#91]
**Is your feature request related to a problem? Please describe.**
com.github.appreciated.apexcharts.ApexChartsBuilder.withYaxis(YAxis) should accept an array like the JavaScript API. 

**Describe the solution you'd like**
Change method to accept a var args list. 

**Additional context**
I can contribute a Pull Request if you will accept one. Please see outline solution below.

-------
    public ApexChartsBuilder withYaxis(YAxis... yaxis) {
        this.yaxis = yaxis;
        return this;
    }

**Comment by error08** [comment]
I would be very happy to have this feature as well!

**Comment by appreciated** [comment]
closed by #119
