### ISSUE TITLE
Adding formatter to Donut/Pie Chart label causes JavaScript Error

### ISSUE THREAD

**Issue by Obi-TP** [appreciated/apexcharts-flow#92]
**Describe the bug**
Adding a formatter via com.github.appreciated.apexcharts.config.plotoptions.pie.builder.ValueBuilder.withFormatter(String) causes JavaScript error **_"TypeError: (0 , t.value.formatter) is not a function"_**.

**Steps or code example to Reproduce**
Sample Code:
		
	private static Labels buildLabels() {		
		
		final String formatter = 	"function doSomeJavaScript(x) { " + 
							"    return x.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");" + 
							"}";
		
		return LabelsBuilder.get()
							.withShow(true)
							.withName(NameBuilder	.get()
											.withColor(ColourCodes.BLACK)
											.withFontSize(LABEL_FONT_PX)
											.build())
							.withValue(ValueBuilder	.get()													
											.withFormatter(formatter)
											.build())
							.build();
	}

**Expected behavior**
A formatted number should appear in the middle of the pie chart e.g. 1,000,000

**Screenshots**
![image](https://user-images.githubusercontent.com/76814984/103418517-f69b3600-4b86-11eb-9f7b-a62a921888d4.png)

**Comment by ILikePhysics** [comment]
I have the same issue while trying to set a formatter on the total label of donut chart.

**Comment by mvysny** [comment]
I think the problem here is that the Java wrapper sends the formatter value as a String while JavaScript side expects a function.

I don't think it's possible to send functions via JSON directly since JSON is not supposed to transfer functions: https://stackoverflow.com/questions/2001449/is-it-valid-to-define-functions-in-json-results

A workaround is needed: e.g. you'll need to attach the functions beforehand, say to the `window` object:
```
window.formatLabelTotal = function() { ... }
```
Then the wrapper code would accept the formatter Strings as function names, such as `window.formatLabelTotal`. However this needs to be implemented.

**Comment by ILikePhysics** [comment]
I am able to set a formatter on other chart and it works.
For example, I do this
`
[...]
.withDataLabels(DataLabelsBuilder.get()
                    .withEnabled(true)
                    .withFormatter(jvmMemFormatterJsFucntion)
                    .build())
[...]
`

With this formatter string:
`
private val jvmMemFormatterJsFucntion =
          """
          function(val, {seriesIndex, dataPointIndex, w}) {              
              return (parseFloat(val).toFixed(2)) + " kB";               
          }    
          """.trimIndent()
`

**Comment by mvysny** [comment]
Excellent find! I can indeed see at `apexcharts-wrapper.js:175` that the plotOptions formatter for pie/donut is not post-processed. Perhaps something like this should be in place:

```
            if (this.plotOptions.pie && this.plotOptions.pie.donut && this.plotOptions.pie.donut.labels && this.plotOptions.pie.donut.labels.total && this.plotOptions.pie.donut.labels.total.formatter) {
                this.plotOptions.pie.donut.labels.total.formatter = this.evalFunction(this.plotOptions.pie.donut.labels.total.formatter);
            }
```

(the same for `this.plotOptions.pie.donut.labels.value`).
