### ISSUE TITLE
Feature request: Is it possible to Implement the funnel chart ?

### ISSUE THREAD

**Issue by ado2000** [appreciated/apexcharts-flow#93]
Nice component friend, you did a good job!

How is it possible to Implement funnel chart?

Thanks

**Comment by appreciated** [comment]
@ado2000 correct me if I'm wrong but isn't the funnel chart of the project partner fusion charts?

**Comment by ado2000** [comment]
oops ... You're right,

https://www.fusioncharts.com/charts/funnel-and-pyramid-charts?utm_source=ac.demos&utm_medium=banner&utm_campaign=apexcharts&utm_content=funnel

I saw them on the Apex Charts sample page and thought it was the Apex chart as well.
https://apexcharts.com/javascript-chart-demos/

**Comment by appreciated** [comment]
They do offer some nice visualizations, but unfortunately, these only come at a price.
